-- Supabase Seed Data for HP Sales Funnel App

-- 1. Insert default target
INSERT INTO targets (id, daily, weekly, monthly, quarterly, yearly)
VALUES ('default', 15000, 100000, 400000, 1200000, 5000000)
ON CONFLICT (id) DO UPDATE SET
  daily = EXCLUDED.daily,
  weekly = EXCLUDED.weekly,
  monthly = EXCLUDED.monthly,
  quarterly = EXCLUDED.quarterly,
  yearly = EXCLUDED.yearly;

-- 2. Insert seed leads
INSERT INTO leads (
  id, org_name, sector, dept_industry, contact_person, phone, email,
  product_category, model, qty, est_value, source, tender_ref, stage,
  expected_close, next_follow_up, sales_person, remarks, created_date, closed_date
) VALUES
(
  'HPQ-MZN001',
  'District Collectorate, Muzaffarnagar',
  'Government',
  'Revenue Dept',
  'R.K. Sharma',
  '9876543210',
  '',
  'MFD (Multi-Function Device)',
  'HP LaserJet MFP M436n',
  12,
  540000,
  'Government Tender (CPPP/eProc)',
  'MZN/2026/IT/017',
  'Technical Evaluation',
  CURRENT_DATE + INTERVAL '10 days',
  CURRENT_DATE + INTERVAL '2 days',
  'RK Jindal',
  'EMD submitted, awaiting technical bid opening.',
  CURRENT_DATE - INTERVAL '18 days',
  NULL
),
(
  'HPQ-SPS002',
  'Sanskriti Public School',
  'Non-Government',
  'Education',
  'Principal Office',
  '9812345670',
  '',
  'LaserJet Printer',
  'HP LaserJet Pro M15w',
  5,
  65000,
  'Referral',
  '',
  'Won',
  CURRENT_DATE - INTERVAL '3 days',
  NULL,
  'RK Jindal',
  'PO received and delivered.',
  CURRENT_DATE - INTERVAL '20 days',
  CURRENT_DATE - INTERVAL '3 days'
),
(
  'HPQ-UMS003',
  'UP State Medical College',
  'Government',
  'Health Dept',
  'Dr. Verma',
  '',
  '',
  'Document Scanner',
  'HP ScanJet Pro N4600',
  8,
  312000,
  'GeM Portal',
  'GEM/2026/B/998231',
  'Quotation / Bid Submitted',
  CURRENT_DATE + INTERVAL '20 days',
  CURRENT_DATE + INTERVAL '5 days',
  'Sales Team',
  'L1 status pending.',
  CURRENT_DATE - INTERVAL '9 days',
  NULL
),
(
  'HPQ-ATP004',
  'Aarohi Textiles Pvt Ltd',
  'Non-Government',
  'Manufacturing',
  'Purchase Mgr',
  '9911223344',
  '',
  'Ink / Toner Cartridge',
  'HP 26A Toner',
  40,
  88000,
  'Existing Customer Repeat',
  '',
  'PO / Work Order Received',
  CURRENT_DATE + INTERVAL '2 days',
  CURRENT_DATE + INTERVAL '1 day',
  'RK Jindal',
  'Repeat monthly order.',
  CURRENT_DATE - INTERVAL '4 days',
  NULL
),
(
  'HPQ-PRD005',
  'Panchayati Raj Dept, Meerut',
  'Government',
  'Rural Development',
  'BDO Office',
  '',
  '',
  'Inkjet Printer',
  'HP Smart Tank 519',
  25,
  275000,
  'Direct Government RFQ',
  'PRD/MRT/26/44',
  'New Lead',
  CURRENT_DATE + INTERVAL '30 days',
  CURRENT_DATE + INTERVAL '3 days',
  'Sales Team',
  'Enquiry received via block office.',
  CURRENT_DATE - INTERVAL '1 day',
  NULL
),
(
  'HPQ-RCM006',
  'Rotary Club Muzaffarnagar Sanskriti',
  'Non-Government',
  'NGO / Community',
  'Secretary',
  '',
  '',
  'MFD (Multi-Function Device)',
  'HP LaserJet MFP M139',
  1,
  22000,
  'Referral',
  '',
  'Lost',
  CURRENT_DATE - INTERVAL '6 days',
  NULL,
  'RK Jindal',
  'Went with a competitor on price.',
  CURRENT_DATE - INTERVAL '15 days',
  CURRENT_DATE - INTERVAL '6 days'
)
ON CONFLICT (id) DO NOTHING;
